### ISSUE TITLE
Unable to load deps.zig

### ISSUE THREAD

**Issue by Bios-Marcel** [nektro/zig-time#7]
Hey Hey

I am probably missing something here as I am new to zig, but I am trying to use the dependency management that's part of zig 0.11.

I am getting the following:

```
C:\Users\marce\AppData\Local\zig\p\1220075a229731ece71614389c84e803b9732e7afae0091b277cb92a69db8077740c\build.zig:2:22: error: unable to load 'C:\Users\marce\AppData\Local\zig\p\1220075a229731ece71614389c84e803b9732e7afae0091b277cb92a69db8077740c\deps.zig': FileNotFound
```

Since your repo does not contain the file, but references it explicitly, I assume I need to get it from somewhere, or write it up myself? I am assuming the lib wasn't meant to be easily consumable yet though?

Could you guide me in a general direction here? Maybe we could then add a small section to the readme, since I might not be the only one failing here :D

**Comment by nektro** [comment]
zig-time uses https://github.com/nektro/zigmod for management not the builtin one
